// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh1jcC6yNuEAgDGjDY6QbPWCW7INMAmaQ',
    appId: '1:587264196362:web:8aad6a12d44adbdfcc44f3',
    messagingSenderId: '587264196362',
    projectId: 'mover-43345',
    authDomain: 'mover-43345.firebaseapp.com',
    storageBucket: 'mover-43345.appspot.com',
    measurementId: 'G-M2CFPV83EY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_k3q0TlKBRJBAMGeg7I04HnvzGuJxCHg',
    appId: '1:587264196362:android:7acecfa66eeec20ecc44f3',
    messagingSenderId: '587264196362',
    projectId: 'mover-43345',
    storageBucket: 'mover-43345.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH5MQ8wZ_rqUoojZYKRCGhy0P_99wCUik',
    appId: '1:587264196362:ios:3d56bc492bc345aecc44f3',
    messagingSenderId: '587264196362',
    projectId: 'mover-43345',
    storageBucket: 'mover-43345.appspot.com',
    iosClientId:
        '587264196362-21ik5h4d8kledrrrapu4rjffr9dnfp1d.apps.googleusercontent.com',
    iosBundleId: 'jp.mover.devillage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDH5MQ8wZ_rqUoojZYKRCGhy0P_99wCUik',
    appId: '1:587264196362:ios:3d56bc492bc345aecc44f3',
    messagingSenderId: '587264196362',
    projectId: 'mover-43345',
    storageBucket: 'mover-43345.appspot.com',
    iosClientId:
        '587264196362-21ik5h4d8kledrrrapu4rjffr9dnfp1d.apps.googleusercontent.com',
    iosBundleId: 'jp.mover.devillage',
  );
}
