name: mover
description: mover

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  amplify_api: ^0.6.0
  amplify_auth_cognito: ^0.6.0
  amplify_datastore: ^0.6.0
  amplify_flutter: ^0.6.0
  bubble_tab_indicator: ^0.1.6
  cached_network_image: ^3.2.1
  carousel_slider: ^4.1.1
  cupertino_icons: ^1.0.2
  device_info_plus: ^3.2.4
  email_validator: ^2.0.1
  firebase_analytics: ^9.1.9
  firebase_core: ^1.17.1
  firebase_messaging: ^11.4.1
  firebase_remote_config: ^2.0.8
  fl_chart: ^0.50.5
  flutter:
    sdk: flutter
  flutter_datetime_picker: ^1.5.1
  flutter_launcher_icons: ^0.9.3
  flutter_local_notifications: ^9.6.0
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_secure_storage: ^5.0.2
  flutter_verification_code: ^1.1.3
  freezed: ^2.0.3+1
  freezed_annotation: ^2.0.3
  getwidget: ^3.0.1
  graphql: ^5.1.1
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  json_annotation: ^4.5.0
  json_serializable: ^6.2.0
  local_auth: ^2.1.0
  lottie: ^1.3.0
  numberpicker: ^2.1.1
  provider: ^6.0.1
  qr_flutter: ^4.0.0
  shimmer: ^2.0.0
  url_launcher: ^6.1.2
  walletconnect_dart: ^0.0.9
  web3dart: null

dev_dependencies:
  build_runner: null

  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icon/
    - assets/lottie/
